//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Тарифы
    {
        public Nullable<int> код__города { get; set; }
        public string название__города { get; set; }
        public Nullable<decimal> тариф___стоимость_1_мин__ { get; set; }
        public string П________ризнак___оплаты { get; set; }
        public int ID_Тарифа { get; set; }
    
        public virtual Разговоры Разговоры { get; set; }
        public virtual Телефон Телефон { get; set; }
    }
}
