//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Телефон
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Телефон()
        {
            this.Тарифы = new HashSet<Тарифы>();
        }
    
        public Nullable<int> Номер_телефона { get; set; }
        public string Номер_договора { get; set; }
        public string Дата___установки_телефона { get; set; }
        public string ID_Телефона { get; set; }
    
        public virtual Абоненты Абоненты { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Тарифы> Тарифы { get; set; }
    }
}
